// GENERATED by web/gen_binding.mjs from examples/cellar_ground.story — do not edit.
//
// The typed host surface for this story (§6.3). Every ground atom is spelled
// here, once, from the compiler's own vocabulary — so a rename in the .story
// breaks this file's regeneration and your typecheck, instead of silently
// interning a fresh always-false atom. Types are JSDoc: no build step, and
// the shipped module is exactly the one that type-checks (§12).

/** @typedef {"hero" | "guard"} T_actor */
/** @typedef {"antidote"} T_item */

export const STORY = "examples/cellar_ground.story";
export const SOURCE_HASH = "c8c5d5a2";
export const SORTS = {"actor":["hero","guard"],"item":["antidote"]};

// #159 exclusive groups, exactly as world_step checks them: a step admits at
// most one member per (group, key). The builder below refuses the second at
// ADD time, naming the order already in the set — a networked host collecting
// orders from remote clients must reject per order, never lose the tick.
const EXCLUSIVE = [];

/** FNV-1a, matching the generator's — the staleness check below. */
function hash(text) {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i) & 0xff;
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}

/**
 * Open a session: compile the story into the WASM core and return the typed
 * surface over it. `M` is the instantiated module (`await createInfeasible()`).
 * @param {any} M
 * @param {string} src   the .story source this binding was generated from
 */
export function open(M, src) {
  const c = (f, ret, args) => M.cwrap(f, ret, args);
  const api = {
    compile: c('inf_compile', 'number', ['string']),
    free: c('inf_free', null, ['number']),
    intern: c('inf_intern', 'number', ['number', 'string']),
    name: c('inf_name', 'string', ['number', 'number']),
    query: c('inf_query', 'number', ['number', 'number', 'number']),
    get: c('inf_get', 'number', ['number', 'number']),
    set: c('inf_set', null, ['number', 'number', 'number']),
    getNum: c('inf_get_num', 'number', ['number', 'number']),
    setNum: c('inf_set_num', null, ['number', 'number', 'number']),
    step: c('inf_step', 'number', ['number', 'number', 'number']),
    why: c('inf_why', 'string', ['number', 'number', 'number']),
    lastErr: c('inf_last_err', 'string', []),
    lastDiag: c('inf_last_diag', 'string', []),
    emitCount: c('inf_emit_count', 'number', ['number']),
    emits: c('inf_emits', 'number', ['number']),
    boolDeltas: c('inf_bool_deltas', 'number', ['number', 'number', 'number']),
    numDeltas: c('inf_num_deltas', 'number', ['number', 'number', 'number']),
    receipt: c('inf_num_receipt', 'number', ['number', 'number', 'number', 'number']),
    subscribe: c('inf_subscribe', 'number', ['number', 'number', 'number']),
    unsubscribe: c('inf_unsubscribe', null, ['number', 'number']),
    subVerdict: c('inf_sub_verdict', 'number', ['number', 'number']),
    subEdges: c('inf_sub_edges', 'number', ['number', 'number', 'number']),
  };
  if (hash(src) !== SOURCE_HASH)
    throw new Error('this binding was generated from a different ' + STORY +
      ' — regenerate it (node web/gen_binding.mjs ' + STORY + '), or its' +
      ' helpers spell atoms this story no longer has and every query' +
      ' answers refuted');
  const s = api.compile(src);
  if (!s) throw new Error('compile failed:\n' + api.lastDiag());

  const ids = new Map();
  const id = (t) => { let v = ids.get(t); if (v === undefined) { v = api.intern(s, t); ids.set(t, v); } return v; };
  const VERDICT = ['undecided', 'proved', 'refuted'];
  const nameOf = (atom) => api.name(s, atom);
  // a ground argument must be a member of its sort: the binding's own
  // vocabulary check, for values that arrive as data rather than literals
  const chk = (sort, v) => {
    const dom = SORTS[sort];
    if (dom && !dom.includes(v))
      throw new TypeError(`'${v}' is not a member of sort '${sort}' (${dom.join(', ')})`);
    return v;
  };

  /** Judgments — derived, never stored (I1). */
  const q = {
    /**
     * @param {T_actor} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    weakened: (a0) => { chk("actor", a0);
      return VERDICT[api.query(s, id(`weakened(${a0})`), 0)]; },
    /**
     * @param {T_actor} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    can_force_door: (a0) => { chk("actor", a0);
      return VERDICT[api.query(s, id(`can_force_door(${a0})`), 0)]; },
  };

  /** Base state — the only mutable thing in the world (I2 says only a step
   *  may change it; these setters are for loading/seeding). */
  const st = {
    /**
     * @param {T_actor} a0
     * @returns {boolean}
     */

    poisoned: (a0) => { chk("actor", a0);
      return !!api.get(s, id(`poisoned(${a0})`)); },
    /**
     * @param {T_actor} a0
     * @param {T_item} a1
     * @returns {boolean}
     */

    holding: (a0, a1) => { chk("actor", a0); chk("item", a1);
      return !!api.get(s, id(`holding(${a0},${a1})`)); },
    /**
     * @param {T_actor} a0
     * @returns {boolean}
     */

    strong: (a0) => { chk("actor", a0);
      return !!api.get(s, id(`strong(${a0})`)); },
    /**
     * @returns {boolean}
     */

    door_closed: () => { 
      return !!api.get(s, id("door_closed")); },
  };

  const set = {
    poisoned: (a0, a1) => { chk("actor", a0);
      api.set(s, id(`poisoned(${a0})`), a1 === false ? 0 : 1); },
    holding: (a0, a1, a2) => { chk("actor", a0); chk("item", a1);
      api.set(s, id(`holding(${a0},${a1})`), a2 === false ? 0 : 1); },
    strong: (a0, a1) => { chk("actor", a0);
      api.set(s, id(`strong(${a0})`), a1 === false ? 0 : 1); },
    door_closed: (a0) => { 
      api.set(s, id("door_closed"), a0 === false ? 0 : 1); },
  };

  /** Action constructors. An unknown or misspelled action is unconstructible
   *  — there is no function to call — which is #119's loud no-op retired at
   *  the interface rather than caught at the step. */
  const a = {
    /**
     * @param {T_actor} X
     */
    force_door: (X) => { chk("actor", X);
      return { action: "force_door", args: { X }, term: `force_door(${X})` }; },
  };

  /** The action set for one step, assembled incrementally (§6.3): the
   *  protocol checks moved to construction time, where a rejection can name
   *  the offending order instead of failing the whole tick. */
  class ActionSet {
    constructor() { this.items = []; }
    add(act) {
      for (const g of EXCLUSIVE) {
        const mine = g.members.find((m) => m.action === act.action);
        if (!mine) continue;
        const key = (m, x) => m.key.map((k) => (k === null ? null : x.args[k])).join('\u0000');
        for (const other of this.items) {
          const theirs = g.members.find((m) => m.action === other.action);
          if (!theirs) continue;
          if (other.term === act.term) return this;   // the same order twice is one order
          if (key(mine, act) === key(theirs, other))
            throw new RangeError(
              `${act.term} is exclusive with ${other.term} already in this step` +
              ` — submit them in separate steps`);
        }
      }
      this.items.push(act);
      return this;
    }
    get length() { return this.items.length; }
  }

  const readCells = (fn, cap) => {
    const p = M._malloc(cap * 4);
    const need = fn(s, p, cap);
    const view = new Int32Array(M.HEAP32.buffer, p, Math.min(need, cap)).slice();
    M._free(p);
    if (need > cap) return readCells(fn, need);   // grow and retry, never truncate
    return view;
  };

  const world = {
    q, state: st, set, a,
    /** A fresh action set for the next step. */
    actions: () => new ActionSet(),
    /** Advance one step. Throws on a rejected step: with the builder
     *  consuming the protocol class, a -1 reaching a bound host is a bug. */
    step(set) {
      const items = set instanceof ActionSet ? set.items : [set];
      const p = M._malloc(Math.max(1, items.length) * 4);
      items.forEach((it, i) => { M.HEAPU32[(p >> 2) + i] = id(it.term); });
      const rc = api.step(s, p, items.length);
      M._free(p);
      if (rc !== 0) throw new Error('step rejected: ' + api.lastErr());
      return world;
    },
    /** Burst cues fired by the last step (#11), as ground atom names. */
    emits() {
      const n = api.emitCount(s);
      if (!n) return [];
      const ptr = api.emits(s);
      return Array.from(new Uint32Array(M.HEAPU32.buffer, ptr, n), nameOf);
    },
    /** What the last step changed (#88): base facts that actually moved. */
    changed() {
      const b = readCells(api.boolDeltas, 64), n = readCells(api.numDeltas, 64);
      const out = [];
      for (let i = 0; i + 1 < b.length; i += 2)
        out.push({ atom: nameOf(b[i]), value: !!b[i + 1] });
      for (let i = 0; i + 2 < n.length; i += 3)
        out.push({ atom: nameOf(n[i]), from: n[i + 1], to: n[i + 2] });
      return out;
    },
    /** How a numeric fluent reached its value in the last step (#88). */
    receipt(term) {
      const cells = readCells((sess, p, cap) => api.receipt(sess, id(term), p, cap), 64);
      if (!cells.length) return null;
      const [base, raw, applied, lo, hi, flags, n] = cells;
      const items = [];
      let k = 7;
      for (let i = 0; i < n; i++) {
        const [op, amount, defeated, pred, nbind] = cells.slice(k, k + 5);
        k += 5;
        const bind = {};
        for (let j = 0; j < nbind; j++, k += 2) bind[nameOf(cells[k])] = nameOf(cells[k + 1]);
        items.push({ op: ['set', 'add', 'sub'][op], amount, defeated: !!defeated,
                     rule: nameOf(pred), bind });
      }
      return { base, raw, applied, lo, hi, hasRange: !!(flags & 1),
               clamped: !!(flags & 2), items };
    },
    /** Register interest in a literal (§11 M2) — one call shape for a base
     *  fact and for a judgment, because a subscription names a conclusion,
     *  not a storage decision. Returns a stable handle. */
    subscribe: (term, neg = false) => api.subscribe(s, id(term), neg ? 1 : 0),
    unsubscribe: (sub) => api.unsubscribe(s, sub),
    /** The LEVEL: what a subscription says right now. */
    verdict: (sub) => VERDICT[api.subVerdict(s, sub)],
    /** The EDGES: which subscriptions flipped in the last step — the `btnp`
     *  to level's `btn`. Decide from the level, react to these. */
    edges() {
      const cells = readCells(api.subEdges, 64);
      const out = [];
      for (let i = 0; i + 4 < cells.length; i += 5)
        out.push({ sub: cells[i], atom: nameOf(cells[i + 1]), neg: !!cells[i + 2],
                   from: VERDICT[cells[i + 3]], to: VERDICT[cells[i + 4]],
                   rose: cells[i + 4] === 1, fell: cells[i + 3] === 1 });
      return out;
    },
    /** The proof/defeat trace for a ground literal — the debugger (§5.1). */
    why: (term, neg = false) => api.why(s, id(term), neg ? 1 : 0),
    close: () => api.free(s),
  };
  return world;
}
