// GENERATED by web/gen_binding.mjs from examples/duel_pure.story — do not edit.
//
// The typed host surface for this story (§6.3). Every ground atom is spelled
// here, once, from the compiler's own vocabulary — so a rename in the .story
// breaks this file's regeneration and your typecheck, instead of silently
// interning a fresh always-false atom. Types are JSDoc: no build step, and
// the shipped module is exactly the one that type-checks (§12).

/** @typedef {"you" | "gnoll" | "imp"} T_fighter */
/** @typedef {"edge_a" | "edge_b" | "spark" | "salve"} T_card */
/** @typedef {string} T_drawable */   // opaque domain: host-minted handles
/** @typedef {"z_hand" | "z_spent"} T_zone */
/** @typedef {"s_you" | "s_gnoll" | "s_imp" | "s_strike" | "s_bolt" | "s_mend"} T_sprite */
/** @typedef {"st_room" | "st_bar" | "st_title" | "st_button" | "st_button_off"} T_style */
/** @typedef {"a_title" | "a_foes" | "a_self" | "a_hand" | "a_bar" | "a_who" | "a_note" | "a_menu" | "a_status"} T_anchor */
/** @typedef {"w_the_duel" | "w_foes" | "w_you" | "w_hand" | "w_energy" | "w_downed" | "w_aimed" | "w_end_turn"} T_word */
/** @typedef {"q_hit" | "q_ward" | "q_heal"} T_cue */
/** @typedef {"snd_thud" | "snd_ring" | "snd_chime"} T_sound */

export const STORY = "examples/duel_pure.story";
export const SOURCE_HASH = "0a81c2a8";
export const SORTS = {"fighter":["you","gnoll","imp"],"card":["edge_a","edge_b","spark","salve"],"drawable":["you","gnoll","imp","edge_a","edge_b","spark","salve"]};
export const UNIONS = {"drawable":["fighter","card"]};
export const ENUMS = {"zone":["z_hand","z_spent"],"sprite":["s_you","s_gnoll","s_imp","s_strike","s_bolt","s_mend"],"style":["st_room","st_bar","st_title","st_button","st_button_off"],"anchor":["a_title","a_foes","a_self","a_hand","a_bar","a_who","a_note","a_menu","a_status"],"word":["w_the_duel","w_foes","w_you","w_hand","w_energy","w_downed","w_aimed","w_end_turn"],"cue":["q_hit","q_ward","q_heal"],"sound":["snd_thud","snd_ring","snd_chime"]};

export const IFACE = {"unions":{"drawable":["fighter","card"]},"judgments":[{"name":"down","args":["fighter"]},{"name":"in_hand","args":["card"]},{"name":"enemy","args":["fighter"]},{"name":"ally","args":["fighter"]},{"name":"target","args":["fighter"]},{"name":"picked","args":["fighter"]},{"name":"aimed","args":["fighter"]},{"name":"panel","args":["anchor","style"]},{"name":"caption","args":["anchor","word"]},{"name":"shows","args":["drawable","sprite"]},{"name":"in_anchor","args":["fighter","anchor"]},{"name":"prop_in","args":["card","anchor"]},{"name":"gauge","args":["anchor","fighter"]},{"name":"gauge_low","args":["fighter"]},{"name":"cue_sound","args":["cue","sound"]}],"state":[{"name":"in_zone","args":["card"],"type":"enum","values":["z_hand","z_spent"]},{"name":"is_strike","args":["card"],"type":"bool"},{"name":"is_bolt","args":["card"],"type":"bool"},{"name":"is_mend","args":["card"],"type":"bool"},{"name":"hostile","args":["fighter"],"type":"bool"},{"name":"alive","args":["fighter"],"type":"bool"},{"name":"hp","args":["fighter"],"type":"int"},{"name":"hp_max","args":["fighter"],"type":"int"},{"name":"energy","args":[],"type":"int"},{"name":"selected","args":["fighter"],"type":"bool"},{"name":"aiming","args":["fighter"],"type":"bool"},{"name":"showing","args":[],"type":"bool"}],"actions":[{"name":"strike","params":["card","fighter"]},{"name":"bolt","params":["card","fighter"]},{"name":"mend","params":["card","fighter"]},{"name":"end_turn","params":[]},{"name":"aim_gnoll","params":[]},{"name":"aim_imp","params":[]},{"name":"aim_you","params":[]}],"values":[{"name":"ax","args":["anchor"]},{"name":"ay","args":["anchor"]},{"name":"aw","args":["anchor"]},{"name":"ah","args":["anchor"]},{"name":"gauge_value","args":["fighter"]},{"name":"gauge_max","args":["fighter"]}]};

// #159 exclusive groups, exactly as world_step checks them: a step admits at
// most one member per (group, key). The builder below refuses the second at
// ADD time, naming the order already in the set — a networked host collecting
// orders from remote clients must reject per order, never lose the tick.
const EXCLUSIVE = [{"members":[{"action":"strike","key":[null,null]},{"action":"bolt","key":[null,null]},{"action":"mend","key":[null,null]},{"action":"end_turn","key":[]}]},{"members":[{"action":"aim_gnoll","key":[]},{"action":"aim_imp","key":[]},{"action":"aim_you","key":[]}]}];

/** FNV-1a, matching the generator's — the staleness check below. */
function hash(text) {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i) & 0xff;
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}

/**
 * Open a session: compile the story into the WASM core and return the typed
 * surface over it. `M` is the instantiated module (`await createInfeasible()`).
 * @param {any} M
 * @param {string} src   the .story source this binding was generated from
 */
export function open(M, src) {
  const c = (f, ret, args) => M.cwrap(f, ret, args);
  const api = {
    compile: c('inf_compile', 'number', ['string']),
    free: c('inf_free', null, ['number']),
    intern: c('inf_intern', 'number', ['number', 'string']),
    name: c('inf_name', 'string', ['number', 'number']),
    query: c('inf_query', 'number', ['number', 'number', 'number']),
    get: c('inf_get', 'number', ['number', 'number']),
    set: c('inf_set', null, ['number', 'number', 'number']),
    getNum: c('inf_get_num', 'number', ['number', 'number']),
    setNum: c('inf_set_num', null, ['number', 'number', 'number']),
    step: c('inf_step', 'number', ['number', 'number', 'number']),
    why: c('inf_why', 'string', ['number', 'number', 'number']),
    lastErr: c('inf_last_err', 'string', []),
    lastDiag: c('inf_last_diag', 'string', []),
    emitCount: c('inf_emit_count', 'number', ['number']),
    emits: c('inf_emits', 'number', ['number']),
    boolDeltas: c('inf_bool_deltas', 'number', ['number', 'number', 'number']),
    numDeltas: c('inf_num_deltas', 'number', ['number', 'number', 'number']),
    receipt: c('inf_num_receipt', 'number', ['number', 'number', 'number', 'number']),
    subscribe: c('inf_subscribe', 'number', ['number', 'number', 'number']),
    unsubscribe: c('inf_unsubscribe', null, ['number', 'number']),
    subVerdict: c('inf_sub_verdict', 'number', ['number', 'number']),
    subEdges: c('inf_sub_edges', 'number', ['number', 'number', 'number']),
    getValue: c('inf_get_value', 'number', ['number', 'number', 'number']),
    actions_: c('inf_actions', 'number', ['number', 'number', 'number']),
    actionStatus: c('inf_action_status', 'number', ['number', 'number']),
    actionBlockers: c('inf_action_blockers', 'number', ['number', 'number', 'number', 'number']),
  };
  if (hash(src) !== SOURCE_HASH)
    throw new Error('this binding was generated from a different ' + STORY +
      ' — regenerate it (node web/gen_binding.mjs ' + STORY + '), or its' +
      ' helpers spell atoms this story no longer has and every query' +
      ' answers refuted');
  const s = api.compile(src);
  if (!s) throw new Error('compile failed:\n' + api.lastDiag());

  const ids = new Map();
  const id = (t) => { let v = ids.get(t); if (v === undefined) { v = api.intern(s, t); ids.set(t, v); } return v; };
  const VERDICT = ['undecided', 'proved', 'refuted'];
  const nameOf = (atom) => api.name(s, atom);
  // a ground argument must be a member of its sort or enum domain: the
  // binding's own vocabulary check, for values that arrive as data rather
  // than literals (a literal is already checked by the JSDoc union type)
  const chk = (sort, v) => {
    const dom = SORTS[sort] ?? ENUMS[sort];
    if (dom && !dom.includes(v))
      throw new TypeError(`'${v}' is not a member of '${sort}' (${dom.join(', ')})`);
    return v;
  };

  /** Judgments — derived, never stored (I1). */
  const q = {
    /**
     * @param {T_fighter} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    down: (a0) => { chk("fighter", a0);
      return VERDICT[api.query(s, id(`down(${a0})`), 0)]; },
    /**
     * @param {T_card} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    in_hand: (a0) => { chk("card", a0);
      return VERDICT[api.query(s, id(`in_hand(${a0})`), 0)]; },
    /**
     * @param {T_fighter} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    enemy: (a0) => { chk("fighter", a0);
      return VERDICT[api.query(s, id(`enemy(${a0})`), 0)]; },
    /**
     * @param {T_fighter} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    ally: (a0) => { chk("fighter", a0);
      return VERDICT[api.query(s, id(`ally(${a0})`), 0)]; },
    /**
     * @param {T_fighter} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    target: (a0) => { chk("fighter", a0);
      return VERDICT[api.query(s, id(`target(${a0})`), 0)]; },
    /**
     * @param {T_fighter} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    picked: (a0) => { chk("fighter", a0);
      return VERDICT[api.query(s, id(`picked(${a0})`), 0)]; },
    /**
     * @param {T_fighter} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    aimed: (a0) => { chk("fighter", a0);
      return VERDICT[api.query(s, id(`aimed(${a0})`), 0)]; },
    /**
     * @param {T_anchor} a0
     * @param {T_style} a1
     * @returns {'undecided'|'proved'|'refuted'}
     */

    panel: (a0, a1) => { chk("anchor", a0); chk("style", a1);
      return VERDICT[api.query(s, id(`panel(${a0},${a1})`), 0)]; },
    /**
     * @param {T_anchor} a0
     * @param {T_word} a1
     * @returns {'undecided'|'proved'|'refuted'}
     */

    caption: (a0, a1) => { chk("anchor", a0); chk("word", a1);
      return VERDICT[api.query(s, id(`caption(${a0},${a1})`), 0)]; },
    /**
     * @param {string} a0
     * @param {T_sprite} a1
     * @returns {'undecided'|'proved'|'refuted'}
     */

    shows: (a0, a1) => { chk("drawable", a0); chk("sprite", a1);
      return VERDICT[api.query(s, id(`shows(${a0},${a1})`), 0)]; },
    /**
     * @param {T_fighter} a0
     * @param {T_anchor} a1
     * @returns {'undecided'|'proved'|'refuted'}
     */

    in_anchor: (a0, a1) => { chk("fighter", a0); chk("anchor", a1);
      return VERDICT[api.query(s, id(`in_anchor(${a0},${a1})`), 0)]; },
    /**
     * @param {T_card} a0
     * @param {T_anchor} a1
     * @returns {'undecided'|'proved'|'refuted'}
     */

    prop_in: (a0, a1) => { chk("card", a0); chk("anchor", a1);
      return VERDICT[api.query(s, id(`prop_in(${a0},${a1})`), 0)]; },
    /**
     * @param {T_anchor} a0
     * @param {T_fighter} a1
     * @returns {'undecided'|'proved'|'refuted'}
     */

    gauge: (a0, a1) => { chk("anchor", a0); chk("fighter", a1);
      return VERDICT[api.query(s, id(`gauge(${a0},${a1})`), 0)]; },
    /**
     * @param {T_fighter} a0
     * @returns {'undecided'|'proved'|'refuted'}
     */

    gauge_low: (a0) => { chk("fighter", a0);
      return VERDICT[api.query(s, id(`gauge_low(${a0})`), 0)]; },
    /**
     * @param {T_cue} a0
     * @param {T_sound} a1
     * @returns {'undecided'|'proved'|'refuted'}
     */

    cue_sound: (a0, a1) => { chk("cue", a0); chk("sound", a1);
      return VERDICT[api.query(s, id(`cue_sound(${a0},${a1})`), 0)]; },
  };

  /** Base state — the only mutable thing in the world (I2 says only a step
   *  may change it; these setters are for loading/seeding). */
  const st = {
    /** @returns {"z_hand" | "z_spent"|undefined} */
    in_zone: (a0) => { chk("card", a0);
      for (const v of ["z_hand","z_spent"])
        if (api.get(s, id(`in_zone(${a0})` + '=' + v))) return v;
      return undefined; },
    /**
     * @param {T_card} a0
     * @returns {boolean}
     */

    is_strike: (a0) => { chk("card", a0);
      return !!api.get(s, id(`is_strike(${a0})`)); },
    /**
     * @param {T_card} a0
     * @returns {boolean}
     */

    is_bolt: (a0) => { chk("card", a0);
      return !!api.get(s, id(`is_bolt(${a0})`)); },
    /**
     * @param {T_card} a0
     * @returns {boolean}
     */

    is_mend: (a0) => { chk("card", a0);
      return !!api.get(s, id(`is_mend(${a0})`)); },
    /**
     * @param {T_fighter} a0
     * @returns {boolean}
     */

    hostile: (a0) => { chk("fighter", a0);
      return !!api.get(s, id(`hostile(${a0})`)); },
    /**
     * @param {T_fighter} a0
     * @returns {boolean}
     */

    alive: (a0) => { chk("fighter", a0);
      return !!api.get(s, id(`alive(${a0})`)); },
    /**
     * @param {T_fighter} a0
     * @returns {number}
     */

    hp: (a0) => { chk("fighter", a0);
      return api.getNum(s, id(`hp(${a0})`)); },
    /**
     * @param {T_fighter} a0
     * @returns {number}
     */

    hp_max: (a0) => { chk("fighter", a0);
      return api.getNum(s, id(`hp_max(${a0})`)); },
    /**
     * @returns {number}
     */

    energy: () => { 
      return api.getNum(s, id("energy")); },
    /**
     * @param {T_fighter} a0
     * @returns {boolean}
     */

    selected: (a0) => { chk("fighter", a0);
      return !!api.get(s, id(`selected(${a0})`)); },
    /**
     * @param {T_fighter} a0
     * @returns {boolean}
     */

    aiming: (a0) => { chk("fighter", a0);
      return !!api.get(s, id(`aiming(${a0})`)); },
    /**
     * @returns {boolean}
     */

    showing: () => { 
      return !!api.get(s, id("showing")); },
  };

  const set = {
    in_zone: (a0, a1) => { chk("card", a0);
      for (const v of ["z_hand","z_spent"])
        api.set(s, id(`in_zone(${a0})` + '=' + v), v === a1 ? 1 : 0); },
    is_strike: (a0, a1) => { chk("card", a0);
      api.set(s, id(`is_strike(${a0})`), a1 === false ? 0 : 1); },
    is_bolt: (a0, a1) => { chk("card", a0);
      api.set(s, id(`is_bolt(${a0})`), a1 === false ? 0 : 1); },
    is_mend: (a0, a1) => { chk("card", a0);
      api.set(s, id(`is_mend(${a0})`), a1 === false ? 0 : 1); },
    hostile: (a0, a1) => { chk("fighter", a0);
      api.set(s, id(`hostile(${a0})`), a1 === false ? 0 : 1); },
    alive: (a0, a1) => { chk("fighter", a0);
      api.set(s, id(`alive(${a0})`), a1 === false ? 0 : 1); },
    hp: (a0, a1) => { chk("fighter", a0);
      api.setNum(s, id(`hp(${a0})`), a1); },
    hp_max: (a0, a1) => { chk("fighter", a0);
      api.setNum(s, id(`hp_max(${a0})`), a1); },
    energy: (a0) => { 
      api.setNum(s, id("energy"), a0); },
    selected: (a0, a1) => { chk("fighter", a0);
      api.set(s, id(`selected(${a0})`), a1 === false ? 0 : 1); },
    aiming: (a0, a1) => { chk("fighter", a0);
      api.set(s, id(`aiming(${a0})`), a1 === false ? 0 : 1); },
    showing: (a0) => { 
      api.set(s, id("showing"), a0 === false ? 0 : 1); },
  };

  /** Ground terms, spelled the way the interface artifact says (§6.3) —
   *  what `subscribe`, `why` and `receipt` take. A multi-valued fluent
   *  takes its value as the last argument, because the ATOM is the
   *  (fluent, value) pair. */
  const lit = {
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    down: (a0) => { chk("fighter", a0);
      return `down(${a0})`; },
    /**
     * @param {T_card} a0
     * @returns {string}
     */

    in_hand: (a0) => { chk("card", a0);
      return `in_hand(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    enemy: (a0) => { chk("fighter", a0);
      return `enemy(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    ally: (a0) => { chk("fighter", a0);
      return `ally(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    target: (a0) => { chk("fighter", a0);
      return `target(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    picked: (a0) => { chk("fighter", a0);
      return `picked(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    aimed: (a0) => { chk("fighter", a0);
      return `aimed(${a0})`; },
    /**
     * @param {T_anchor} a0
     * @param {T_style} a1
     * @returns {string}
     */

    panel: (a0, a1) => { chk("anchor", a0); chk("style", a1);
      return `panel(${a0},${a1})`; },
    /**
     * @param {T_anchor} a0
     * @param {T_word} a1
     * @returns {string}
     */

    caption: (a0, a1) => { chk("anchor", a0); chk("word", a1);
      return `caption(${a0},${a1})`; },
    /**
     * @param {string} a0
     * @param {T_sprite} a1
     * @returns {string}
     */

    shows: (a0, a1) => { chk("drawable", a0); chk("sprite", a1);
      return `shows(${a0},${a1})`; },
    /**
     * @param {T_fighter} a0
     * @param {T_anchor} a1
     * @returns {string}
     */

    in_anchor: (a0, a1) => { chk("fighter", a0); chk("anchor", a1);
      return `in_anchor(${a0},${a1})`; },
    /**
     * @param {T_card} a0
     * @param {T_anchor} a1
     * @returns {string}
     */

    prop_in: (a0, a1) => { chk("card", a0); chk("anchor", a1);
      return `prop_in(${a0},${a1})`; },
    /**
     * @param {T_anchor} a0
     * @param {T_fighter} a1
     * @returns {string}
     */

    gauge: (a0, a1) => { chk("anchor", a0); chk("fighter", a1);
      return `gauge(${a0},${a1})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    gauge_low: (a0) => { chk("fighter", a0);
      return `gauge_low(${a0})`; },
    /**
     * @param {T_cue} a0
     * @param {T_sound} a1
     * @returns {string}
     */

    cue_sound: (a0, a1) => { chk("cue", a0); chk("sound", a1);
      return `cue_sound(${a0},${a1})`; },
    /** @param {"z_hand" | "z_spent"} a1 */
    in_zone: (a0, a1) => { chk("card", a0);
      if (!["z_hand","z_spent"].includes(a1))
        throw new TypeError(`'${a1}' is not a value of 'in_zone'`);
      return `in_zone(${a0})` + '=' + a1; },
    /**
     * @param {T_card} a0
     * @returns {string}
     */

    is_strike: (a0) => { chk("card", a0);
      return `is_strike(${a0})`; },
    /**
     * @param {T_card} a0
     * @returns {string}
     */

    is_bolt: (a0) => { chk("card", a0);
      return `is_bolt(${a0})`; },
    /**
     * @param {T_card} a0
     * @returns {string}
     */

    is_mend: (a0) => { chk("card", a0);
      return `is_mend(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    hostile: (a0) => { chk("fighter", a0);
      return `hostile(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    alive: (a0) => { chk("fighter", a0);
      return `alive(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    hp: (a0) => { chk("fighter", a0);
      return `hp(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    hp_max: (a0) => { chk("fighter", a0);
      return `hp_max(${a0})`; },
    /**
     * @returns {string}
     */

    energy: () => { 
      return "energy"; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    selected: (a0) => { chk("fighter", a0);
      return `selected(${a0})`; },
    /**
     * @param {T_fighter} a0
     * @returns {string}
     */

    aiming: (a0) => { chk("fighter", a0);
      return `aiming(${a0})`; },
    /**
     * @returns {string}
     */

    showing: () => { 
      return "showing"; },
  };

  /** Derived numbers (#82), evaluated against current state. `undefined`
   *  means the value has no applicable definition (#116), not zero. */
  const val = {
    /**
     * @param {T_anchor} a0
     * @returns {number|undefined}
     */

    ax: (a0) => { chk("anchor", a0);
      return readValue(id(`ax(${a0})`)); },
    /**
     * @param {T_anchor} a0
     * @returns {number|undefined}
     */

    ay: (a0) => { chk("anchor", a0);
      return readValue(id(`ay(${a0})`)); },
    /**
     * @param {T_anchor} a0
     * @returns {number|undefined}
     */

    aw: (a0) => { chk("anchor", a0);
      return readValue(id(`aw(${a0})`)); },
    /**
     * @param {T_anchor} a0
     * @returns {number|undefined}
     */

    ah: (a0) => { chk("anchor", a0);
      return readValue(id(`ah(${a0})`)); },
    /**
     * @param {T_fighter} a0
     * @returns {number|undefined}
     */

    gauge_value: (a0) => { chk("fighter", a0);
      return readValue(id(`gauge_value(${a0})`)); },
    /**
     * @param {T_fighter} a0
     * @returns {number|undefined}
     */

    gauge_max: (a0) => { chk("fighter", a0);
      return readValue(id(`gauge_max(${a0})`)); },
  };

  /** Action constructors. An unknown or misspelled action is unconstructible
   *  — there is no function to call — which is #119's loud no-op retired at
   *  the interface rather than caught at the step. */
  const a = {
    /**
     * @param {T_card} C
     * @param {T_fighter} T
     */
    strike: (C, T) => { chk("card", C); chk("fighter", T);
      return { action: "strike", args: { C, T }, term: `strike(${C},${T})` }; },
    /**
     * @param {T_card} C
     * @param {T_fighter} T
     */
    bolt: (C, T) => { chk("card", C); chk("fighter", T);
      return { action: "bolt", args: { C, T }, term: `bolt(${C},${T})` }; },
    /**
     * @param {T_card} C
     * @param {T_fighter} T
     */
    mend: (C, T) => { chk("card", C); chk("fighter", T);
      return { action: "mend", args: { C, T }, term: `mend(${C},${T})` }; },
    end_turn: () => { 
      return { action: "end_turn", args: {  }, term: "end_turn" }; },
    aim_gnoll: () => { 
      return { action: "aim_gnoll", args: {  }, term: "aim_gnoll" }; },
    aim_imp: () => { 
      return { action: "aim_imp", args: {  }, term: "aim_imp" }; },
    aim_you: () => { 
      return { action: "aim_you", args: {  }, term: "aim_you" }; },
  };

  /** The action set for one step, assembled incrementally (§6.3): the
   *  protocol checks moved to construction time, where a rejection can name
   *  the offending order instead of failing the whole tick. */
  class ActionSet {
    constructor() { this.items = []; }
    add(act) {
      for (const g of EXCLUSIVE) {
        const mine = g.members.find((m) => m.action === act.action);
        if (!mine) continue;
        const key = (m, x) => m.key.map((k) => (k === null ? null : x.args[k])).join('\u0000');
        for (const other of this.items) {
          const theirs = g.members.find((m) => m.action === other.action);
          if (!theirs) continue;
          if (other.term === act.term) return this;   // the same order twice is one order
          if (key(mine, act) === key(theirs, other))
            throw new RangeError(
              `${act.term} is exclusive with ${other.term} already in this step` +
              ` — submit them in separate steps`);
        }
      }
      this.items.push(act);
      return this;
    }
    get length() { return this.items.length; }
  }

  /** One number out of WASM: a scratch double the shim fills. */
  const readValue = (atom) => {
    const p = M._malloc(8);
    const ok = api.getValue(s, atom, p);
    const v = ok ? new Float64Array(M.HEAPF64.buffer, p, 1)[0] : undefined;
    M._free(p);
    return v;
  };

  const readCells = (fn, cap) => {
    const p = M._malloc(cap * 4);
    const need = fn(s, p, cap);
    const view = new Int32Array(M.HEAP32.buffer, p, Math.min(need, cap)).slice();
    M._free(p);
    if (need > cap) return readCells(fn, need);   // grow and retry, never truncate
    return view;
  };

  const world = {
    q, state: st, set, a, lit, value: val,
    /** A fresh action set for the next step. */
    actions: () => new ActionSet(),
    /** Advance one step from already-validated TERMS — the replay and
     *  network path. The builder's protocol checks (#159) ran when the
     *  orders were first collected; re-running them against a log whose
     *  argument bindings are gone would compare undefined keys and refuse
     *  a set the world already accepted. */
    stepTerms(terms) {
      const p = M._malloc(Math.max(1, terms.length) * 4);
      terms.forEach((t, i) => { M.HEAPU32[(p >> 2) + i] = id(t); });
      const rc = api.step(s, p, terms.length);
      M._free(p);
      if (rc !== 0) throw new Error('step rejected: ' + api.lastErr());
      return world;
    },
    /** Advance one step. Throws on a rejected step: with the builder
     *  consuming the protocol class, a -1 reaching a bound host is a bug. */
    step(set) {
      const items = set instanceof ActionSet ? set.items : [set];
      const p = M._malloc(Math.max(1, items.length) * 4);
      items.forEach((it, i) => { M.HEAPU32[(p >> 2) + i] = id(it.term); });
      const rc = api.step(s, p, items.length);
      M._free(p);
      if (rc !== 0) throw new Error('step rejected: ' + api.lastErr());
      return world;
    },
    /** Burst cues fired by the last step (#11), as ground atom names. */
    emits() {
      const n = api.emitCount(s);
      if (!n) return [];
      const ptr = api.emits(s);
      return Array.from(new Uint32Array(M.HEAPU32.buffer, ptr, n), nameOf);
    },
    /** What the last step changed (#88): base facts that actually moved. */
    changed() {
      const b = readCells(api.boolDeltas, 64), n = readCells(api.numDeltas, 64);
      const out = [];
      for (let i = 0; i + 1 < b.length; i += 2)
        out.push({ atom: nameOf(b[i]), value: !!b[i + 1] });
      for (let i = 0; i + 2 < n.length; i += 3)
        out.push({ atom: nameOf(n[i]), from: n[i + 1], to: n[i + 2] });
      return out;
    },
    /** How a numeric fluent reached its value in the last step (#88). */
    receipt(term) {
      const cells = readCells((sess, p, cap) => api.receipt(sess, id(term), p, cap), 64);
      if (!cells.length) return null;
      const [base, raw, applied, lo, hi, flags, n] = cells;
      const items = [];
      let k = 7;
      for (let i = 0; i < n; i++) {
        const [op, amount, defeated, pred, nbind] = cells.slice(k, k + 5);
        k += 5;
        const bind = {};
        for (let j = 0; j < nbind; j++, k += 2) bind[nameOf(cells[k])] = nameOf(cells[k + 1]);
        items.push({ op: ['set', 'add', 'sub'][op], amount, defeated: !!defeated,
                     rule: nameOf(pred), bind });
      }
      return { base, raw, applied, lo, hi, hasRange: !!(flags & 1),
               clamped: !!(flags & 2), items };
    },
    /** Register interest in a literal (§11 M2) — one call shape for a base
     *  fact and for a judgment, because a subscription names a conclusion,
     *  not a storage decision. Returns a stable handle. */
    subscribe: (term, neg = false) => api.subscribe(s, id(term), neg ? 1 : 0),
    unsubscribe: (sub) => api.unsubscribe(s, sub),
    /** The LEVEL: what a subscription says right now. */
    verdict: (sub) => VERDICT[api.subVerdict(s, sub)],
    /** The EDGES: which subscriptions flipped in the last step — the `btnp`
     *  to level's `btn`. Decide from the level, react to these. */
    edges() {
      const cells = readCells(api.subEdges, 64);
      const out = [];
      for (let i = 0; i + 4 < cells.length; i += 5)
        out.push({ sub: cells[i], atom: nameOf(cells[i + 1]), neg: !!cells[i + 2],
                   from: VERDICT[cells[i + 3]], to: VERDICT[cells[i + 4]],
                   rose: cells[i + 4] === 1, fell: cells[i + 3] === 1 });
      return out;
    },
    /** THE MENU, answered by the engine (§6.3): every ground action the
     *  world has a rule for, with whether it applies now and — when it does
     *  not — the guards that refused it, each an ordinary literal so
     *  `why` on one prints the argument. A client that writes a judgment
     *  beside every action to mirror its own `requires` has written the
     *  rule twice and may drift; this is the engine's own answer. */
    menu(all = false) {
      const ids = readCells(api.actions_, 64);
      const STATUS = ['applies', 'blocked', 'speculative', 'unknown'];
      const out = [];
      for (const id of ids) {
        const status = STATUS[api.actionStatus(s, id)];
        if (!all && status === 'unknown') continue;
        const term = nameOf(id);
        const item = { term, status, ok: status === 'applies' };
        if (status === 'blocked') {
          const cells = readCells((sess, p, cap) => api.actionBlockers(sess, id, p, cap), 16);
          item.blockers = [];
          for (let i = 0; i + 1 < cells.length; i += 2)
            item.blockers.push({ atom: nameOf(cells[i]), neg: !!cells[i + 1] });
        }
        out.push(item);
      }
      return out;
    },
    /** The proof/defeat trace for a ground literal — the debugger (§5.1). */
    why: (term, neg = false) => api.why(s, id(term), neg ? 1 : 0),
    close: () => api.free(s),
  };
  return world;
}
