// gen_binding.mjs — the §6.3 typed host binding, generated from the interface
// artifact.
//
//   node web/gen_binding.mjs examples/cellar_ground.story [web/out.binding.mjs]
//
// The problem it exists to solve: the intern table gives every host the silent
// failure mode the orphan pass exists to kill. `inf.query(s, inf.intern(s,
// "can_atack_goblin"))` interns a fresh, always-false atom and reports REFUTED
// forever. Codegen closes it protobuf-style — typed constructors and helpers
// over the declared vocabulary — so renaming a fluent in `.story` breaks the
// host's typecheck instead of silently never firing.
//
// What comes out is PLAIN ES-module JS that runs as-is, with its types carried
// as JSDoc annotations that `tsc --checkJs` and any editor consume with no
// build step (§12's buildless rule applied to the host layer): the type
// checking is a dev-time view over the same JS that ships, never a compile of a
// separate source. The generator itself is dev-time tooling — the shipped cart
// is the .story source plus this generated module.

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

const [, , storyPath, outPath] = process.argv;
if (!storyPath) {
  console.error('usage: node web/gen_binding.mjs <file.story> [out.binding.mjs]');
  process.exit(2);
}
const out = outPath ??
  new URL(`./${storyPath.split('/').pop().replace(/\.story$/, '')}.binding.mjs`,
          import.meta.url).pathname;

// ---- compile, and take the artifact -----------------------------------------
const createInfeasible = require('./infeasible.cjs');
const M = await createInfeasible();
const inf = {
  compile: M.cwrap('inf_compile', 'number', ['string']),
  free: M.cwrap('inf_free', null, ['number']),
  iface: M.cwrap('inf_interface', 'string', ['number']),
  diag: M.cwrap('inf_last_diag', 'string', []),
};

const src = readFileSync(storyPath, 'utf8');
const session = inf.compile(src);
if (!session) {
  console.error(`compile failed:\n${inf.diag()}`);
  process.exit(1);
}
const iface = JSON.parse(inf.iface(session));
inf.free(session);
// the session compiled from a string, so the artifact's own `story` is the
// host placeholder; the path we were pointed at is the honest provenance
iface.story = storyPath;

// FNV-1a over the source. The binding checks it at open(): a story edited
// without regenerating would otherwise fail SILENTLY — stale helpers spelling
// atoms the world no longer has, answering REFUTED forever, which is the exact
// failure mode this whole surface exists to kill. Cheap, and it makes "a rename
// in .story breaks the host" true at runtime as well as in the typechecker.
function fnv1a(text) {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i) & 0xff;
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}
const SOURCE_HASH = fnv1a(src);

// ---- helpers ----------------------------------------------------------------
const jsName = (n) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n) ? n : JSON.stringify(n));
const union = (names) => (names.length ? names.map((e) => JSON.stringify(e)).join(' | ') : 'never');
const sortOf = (name) => iface.sorts.find((s) => s.name === name);
const enumOf = (name) => iface.enums.find((e) => e.name === name);

/** The JSDoc type for one argument sort: a literal union of entity names where
 *  the sort is enumerable, `number` for int, and a loose string where the host
 *  mints the values (an opaque `domain`, §5.6). */
function typeOf(sort) {
  if (sort === 'int') return 'number';
  const s = sortOf(sort);
  if (s && s.kind === 'sort') return `T_${s.name}`;
  const e = enumOf(sort);
  if (e) return `T_${e.name}`;
  return 'string';   // an opaque domain handle, or an unresolved sort
}

const params = (args) => args.map((_, i) => `a${i}`);
/** A ground term as the artifact spells it: `pred(a,b)`, bare at arity 0. */
const term = (name, args) =>
  args.length ? `\`${name}(\${${params(args).join('},${')}})\`` : JSON.stringify(name);

function jsdoc(args, ret) {
  const lines = args.map((s, i) => `   * @param {${typeOf(s)}} a${i}`);
  if (ret) lines.push(`   * @returns {${ret}}`);
  return lines.length ? `  /**\n${lines.join('\n')}\n   */\n` : '';
}

// ---- the module -------------------------------------------------------------
const L = [];
const w = (s = '') => L.push(s);

w(`// GENERATED by web/gen_binding.mjs from ${iface.story} — do not edit.`);
w(`//`);
w(`// The typed host surface for this story (§6.3). Every ground atom is spelled`);
w(`// here, once, from the compiler's own vocabulary — so a rename in the .story`);
w(`// breaks this file's regeneration and your typecheck, instead of silently`);
w(`// interning a fresh always-false atom. Types are JSDoc: no build step, and`);
w(`// the shipped module is exactly the one that type-checks (§12).`);
w();
for (const s of iface.sorts) {
  if (s.kind === 'sort') w(`/** @typedef {${union(s.entities)}} T_${s.name} */`);
  else w(`/** @typedef {string} T_${s.name} */   // opaque domain: host-minted handles`);
}
for (const e of iface.enums) w(`/** @typedef {${union(e.values)}} T_${e.name} */`);
w();
w(`export const STORY = ${JSON.stringify(iface.story)};`);
w(`export const SOURCE_HASH = ${JSON.stringify(SOURCE_HASH)};`);
w(`export const SORTS = ${JSON.stringify(
  Object.fromEntries(iface.sorts.filter((s) => s.kind === 'sort')
                                .map((s) => [s.name, s.entities])))};`);
w();

// the exclusive-group protocol, as data the builder enforces
w(`// #159 exclusive groups, exactly as world_step checks them: a step admits at`);
w(`// most one member per (group, key). The builder below refuses the second at`);
w(`// ADD time, naming the order already in the set — a networked host collecting`);
w(`// orders from remote clients must reject per order, never lose the tick.`);
w(`const EXCLUSIVE = ${JSON.stringify(iface.exclusive)};`);
w();

w(`/** FNV-1a, matching the generator's — the staleness check below. */`);
w(`function hash(text) {`);
w(`  let h = 0x811c9dc5;`);
w(`  for (let i = 0; i < text.length; i++) {`);
w(`    h ^= text.charCodeAt(i) & 0xff;`);
w(`    h = Math.imul(h, 0x01000193) >>> 0;`);
w(`  }`);
w(`  return h.toString(16).padStart(8, '0');`);
w(`}`);
w();
w(`/**`);
w(` * Open a session: compile the story into the WASM core and return the typed`);
w(` * surface over it. \`M\` is the instantiated module (\`await createInfeasible()\`).`);
w(` * @param {any} M`);
w(` * @param {string} src   the .story source this binding was generated from`);
w(` */`);
w(`export function open(M, src) {`);
w(`  const c = (f, ret, args) => M.cwrap(f, ret, args);`);
w(`  const api = {`);
w(`    compile: c('inf_compile', 'number', ['string']),`);
w(`    free: c('inf_free', null, ['number']),`);
w(`    intern: c('inf_intern', 'number', ['number', 'string']),`);
w(`    name: c('inf_name', 'string', ['number', 'number']),`);
w(`    query: c('inf_query', 'number', ['number', 'number', 'number']),`);
w(`    get: c('inf_get', 'number', ['number', 'number']),`);
w(`    set: c('inf_set', null, ['number', 'number', 'number']),`);
w(`    getNum: c('inf_get_num', 'number', ['number', 'number']),`);
w(`    setNum: c('inf_set_num', null, ['number', 'number', 'number']),`);
w(`    step: c('inf_step', 'number', ['number', 'number', 'number']),`);
w(`    why: c('inf_why', 'string', ['number', 'number', 'number']),`);
w(`    lastErr: c('inf_last_err', 'string', []),`);
w(`    lastDiag: c('inf_last_diag', 'string', []),`);
w(`    emitCount: c('inf_emit_count', 'number', ['number']),`);
w(`    emits: c('inf_emits', 'number', ['number']),`);
w(`    boolDeltas: c('inf_bool_deltas', 'number', ['number', 'number', 'number']),`);
w(`    numDeltas: c('inf_num_deltas', 'number', ['number', 'number', 'number']),`);
w(`    receipt: c('inf_num_receipt', 'number', ['number', 'number', 'number', 'number']),`);
w(`    subscribe: c('inf_subscribe', 'number', ['number', 'number', 'number']),`);
w(`    unsubscribe: c('inf_unsubscribe', null, ['number', 'number']),`);
w(`    subVerdict: c('inf_sub_verdict', 'number', ['number', 'number']),`);
w(`    subEdges: c('inf_sub_edges', 'number', ['number', 'number', 'number']),`);
w(`  };`);
w(`  if (hash(src) !== SOURCE_HASH)`);
w(`    throw new Error('this binding was generated from a different ' + STORY +`);
w(`      ' — regenerate it (node web/gen_binding.mjs ' + STORY + '), or its' +`);
w(`      ' helpers spell atoms this story no longer has and every query' +`);
w(`      ' answers refuted');`);
w(`  const s = api.compile(src);`);
w(`  if (!s) throw new Error('compile failed:\\n' + api.lastDiag());`);
w();
w(`  const ids = new Map();`);
w(`  const id = (t) => { let v = ids.get(t); if (v === undefined) { v = api.intern(s, t); ids.set(t, v); } return v; };`);
w(`  const VERDICT = ['undecided', 'proved', 'refuted'];`);
w(`  const nameOf = (atom) => api.name(s, atom);`);
w(`  // a ground argument must be a member of its sort: the binding's own`);
w(`  // vocabulary check, for values that arrive as data rather than literals`);
w(`  const chk = (sort, v) => {`);
w(`    const dom = SORTS[sort];`);
w(`    if (dom && !dom.includes(v))`);
w(`      throw new TypeError(\`'\${v}' is not a member of sort '\${sort}' (\${dom.join(', ')})\`);`);
w(`    return v;`);
w(`  };`);
w();

// --- queries over judgments
w(`  /** Judgments — derived, never stored (I1). */`);
w(`  const q = {`);
for (const j of iface.judgments) {
  w(jsdoc(j.args, `'undecided'|'proved'|'refuted'`).replace(/^ {2}/gm, '    '));
  const chks = j.args.map((sort, i) => `chk(${JSON.stringify(sort)}, a${i});`).join(' ');
  w(`    ${jsName(j.name)}: (${params(j.args).join(', ')}) => { ${chks}`);
  w(`      return VERDICT[api.query(s, id(${term(j.name, j.args)}), 0)]; },`);
}
w(`  };`);
w();

// --- state readers/writers
w(`  /** Base state — the only mutable thing in the world (I2 says only a step`);
w(`   *  may change it; these setters are for loading/seeding). */`);
w(`  const st = {`);
for (const f of iface.state) {
  const args = f.args;
  const chks = args.map((sort, i) => `chk(${JSON.stringify(sort)}, a${i});`).join(' ');
  if (f.type === 'bool') {
    w(jsdoc(args, 'boolean').replace(/^ {2}/gm, '    '));
    w(`    ${jsName(f.name)}: (${params(args).join(', ')}) => { ${chks}`);
    w(`      return !!api.get(s, id(${term(f.name, args)})); },`);
  } else if (f.type === 'int' || f.type === 'cell') {
    w(jsdoc(args, 'number').replace(/^ {2}/gm, '    '));
    w(`    ${jsName(f.name)}: (${params(args).join(', ')}) => { ${chks}`);
    w(`      return api.getNum(s, id(${term(f.name, args)})); },`);
  } else if (f.type === 'enum') {
    w(`    /** @returns {${union(f.values)}|undefined} */`);
    w(`    ${jsName(f.name)}: (${params(args).join(', ')}) => { ${chks}`);
    w(`      for (const v of ${JSON.stringify(f.values)})`);
    w(`        if (api.get(s, id(${term(f.name, args)} + '=' + v))) return v;`);
    w(`      return undefined; },`);
  }
}
w(`  };`);
w();
w(`  const set = {`);
for (const f of iface.state) {
  const args = f.args;
  const chks = args.map((sort, i) => `chk(${JSON.stringify(sort)}, a${i});`).join(' ');
  const last = `a${args.length}`;
  if (f.type === 'bool') {
    w(`    ${jsName(f.name)}: (${[...params(args), last].join(', ')}) => { ${chks}`);
    w(`      api.set(s, id(${term(f.name, args)}), ${last} === false ? 0 : 1); },`);
  } else if (f.type === 'int' || f.type === 'cell') {
    w(`    ${jsName(f.name)}: (${[...params(args), last].join(', ')}) => { ${chks}`);
    w(`      api.setNum(s, id(${term(f.name, args)}), ${last}); },`);
  } else if (f.type === 'enum') {
    w(`    ${jsName(f.name)}: (${[...params(args), last].join(', ')}) => { ${chks}`);
    w(`      for (const v of ${JSON.stringify(f.values)})`);
    w(`        api.set(s, id(${term(f.name, args)} + '=' + v), v === ${last} ? 1 : 0); },`);
  }
}
w(`  };`);
w();

// --- action constructors
w(`  /** Action constructors. An unknown or misspelled action is unconstructible`);
w(`   *  — there is no function to call — which is #119's loud no-op retired at`);
w(`   *  the interface rather than caught at the step. */`);
w(`  const a = {`);
for (const act of iface.actions) {
  const args = act.params.map((p) => p.sort);
  const names = act.params.map((p) => p.name);
  if (args.length) {
    w(`    /**`);
    act.params.forEach((p, i) => w(`     * @param {${typeOf(p.sort)}} ${jsName(p.name)}`));
    w(`     */`);
  }
  const formal = names.length ? names.map(jsName).join(', ') : '';
  const chks = act.params.map((p) => `chk(${JSON.stringify(p.sort)}, ${jsName(p.name)});`).join(' ');
  const gterm = names.length
    ? `\`${act.name}(\${${names.map(jsName).join('},${')}})\``
    : JSON.stringify(act.name);
  w(`    ${jsName(act.name)}: (${formal}) => { ${chks}`);
  w(`      return { action: ${JSON.stringify(act.name)}, args: { ${
        names.map((n) => `${jsName(n)}`).join(', ')} }, term: ${gterm} }; },`);
}
w(`  };`);
w();

// --- the action-set builder
w(`  /** The action set for one step, assembled incrementally (§6.3): the`);
w(`   *  protocol checks moved to construction time, where a rejection can name`);
w(`   *  the offending order instead of failing the whole tick. */`);
w(`  class ActionSet {`);
w(`    constructor() { this.items = []; }`);
w(`    add(act) {`);
w(`      for (const g of EXCLUSIVE) {`);
w(`        const mine = g.members.find((m) => m.action === act.action);`);
w(`        if (!mine) continue;`);
w(`        const key = (m, x) => m.key.map((k) => (k === null ? null : x.args[k])).join('\\u0000');`);
w(`        for (const other of this.items) {`);
w(`          const theirs = g.members.find((m) => m.action === other.action);`);
w(`          if (!theirs) continue;`);
w(`          if (other.term === act.term) return this;   // the same order twice is one order`);
w(`          if (key(mine, act) === key(theirs, other))`);
w(`            throw new RangeError(`);
w(`              \`\${act.term} is exclusive with \${other.term} already in this step\` +`);
w(`              \` — submit them in separate steps\`);`);
w(`        }`);
w(`      }`);
w(`      this.items.push(act);`);
w(`      return this;`);
w(`    }`);
w(`    get length() { return this.items.length; }`);
w(`  }`);
w();

// --- step + readouts
w(`  const readCells = (fn, cap) => {`);
w(`    const p = M._malloc(cap * 4);`);
w(`    const need = fn(s, p, cap);`);
w(`    const view = new Int32Array(M.HEAP32.buffer, p, Math.min(need, cap)).slice();`);
w(`    M._free(p);`);
w(`    if (need > cap) return readCells(fn, need);   // grow and retry, never truncate`);
w(`    return view;`);
w(`  };`);
w();
w(`  const world = {`);
w(`    q, state: st, set, a,`);
w(`    /** A fresh action set for the next step. */`);
w(`    actions: () => new ActionSet(),`);
w(`    /** Advance one step. Throws on a rejected step: with the builder`);
w(`     *  consuming the protocol class, a -1 reaching a bound host is a bug. */`);
w(`    step(set) {`);
w(`      const items = set instanceof ActionSet ? set.items : [set];`);
w(`      const p = M._malloc(Math.max(1, items.length) * 4);`);
w(`      items.forEach((it, i) => { M.HEAPU32[(p >> 2) + i] = id(it.term); });`);
w(`      const rc = api.step(s, p, items.length);`);
w(`      M._free(p);`);
w(`      if (rc !== 0) throw new Error('step rejected: ' + api.lastErr());`);
w(`      return world;`);
w(`    },`);
w(`    /** Burst cues fired by the last step (#11), as ground atom names. */`);
w(`    emits() {`);
w(`      const n = api.emitCount(s);`);
w(`      if (!n) return [];`);
w(`      const ptr = api.emits(s);`);
w(`      return Array.from(new Uint32Array(M.HEAPU32.buffer, ptr, n), nameOf);`);
w(`    },`);
w(`    /** What the last step changed (#88): base facts that actually moved. */`);
w(`    changed() {`);
w(`      const b = readCells(api.boolDeltas, 64), n = readCells(api.numDeltas, 64);`);
w(`      const out = [];`);
w(`      for (let i = 0; i + 1 < b.length; i += 2)`);
w(`        out.push({ atom: nameOf(b[i]), value: !!b[i + 1] });`);
w(`      for (let i = 0; i + 2 < n.length; i += 3)`);
w(`        out.push({ atom: nameOf(n[i]), from: n[i + 1], to: n[i + 2] });`);
w(`      return out;`);
w(`    },`);
w(`    /** How a numeric fluent reached its value in the last step (#88). */`);
w(`    receipt(term) {`);
w(`      const cells = readCells((sess, p, cap) => api.receipt(sess, id(term), p, cap), 64);`);
w(`      if (!cells.length) return null;`);
w(`      const [base, raw, applied, lo, hi, flags, n] = cells;`);
w(`      const items = [];`);
w(`      let k = 7;`);
w(`      for (let i = 0; i < n; i++) {`);
w(`        const [op, amount, defeated, pred, nbind] = cells.slice(k, k + 5);`);
w(`        k += 5;`);
w(`        const bind = {};`);
w(`        for (let j = 0; j < nbind; j++, k += 2) bind[nameOf(cells[k])] = nameOf(cells[k + 1]);`);
w(`        items.push({ op: ['set', 'add', 'sub'][op], amount, defeated: !!defeated,`);
w(`                     rule: nameOf(pred), bind });`);
w(`      }`);
w(`      return { base, raw, applied, lo, hi, hasRange: !!(flags & 1),`);
w(`               clamped: !!(flags & 2), items };`);
w(`    },`);
w(`    /** Register interest in a literal (§11 M2) — one call shape for a base`);
w(`     *  fact and for a judgment, because a subscription names a conclusion,`);
w(`     *  not a storage decision. Returns a stable handle. */`);
w(`    subscribe: (term, neg = false) => api.subscribe(s, id(term), neg ? 1 : 0),`);
w(`    unsubscribe: (sub) => api.unsubscribe(s, sub),`);
w(`    /** The LEVEL: what a subscription says right now. */`);
w(`    verdict: (sub) => VERDICT[api.subVerdict(s, sub)],`);
w(`    /** The EDGES: which subscriptions flipped in the last step — the \`btnp\``);
w(`     *  to level's \`btn\`. Decide from the level, react to these. */`);
w(`    edges() {`);
w(`      const cells = readCells(api.subEdges, 64);`);
w(`      const out = [];`);
w(`      for (let i = 0; i + 4 < cells.length; i += 5)`);
w(`        out.push({ sub: cells[i], atom: nameOf(cells[i + 1]), neg: !!cells[i + 2],`);
w(`                   from: VERDICT[cells[i + 3]], to: VERDICT[cells[i + 4]],`);
w(`                   rose: cells[i + 4] === 1, fell: cells[i + 3] === 1 });`);
w(`      return out;`);
w(`    },`);
w(`    /** The proof/defeat trace for a ground literal — the debugger (§5.1). */`);
w(`    why: (term, neg = false) => api.why(s, id(term), neg ? 1 : 0),`);
w(`    close: () => api.free(s),`);
w(`  };`);
w(`  return world;`);
w(`}`);
w();

writeFileSync(out, L.join('\n'));
console.error(`generated ${out} from ${iface.story}`);
